### PR TITLE
Add providing OpenAPI specification(yaml) for northbound API in code-first manner.

### LINKED ISSUE #45: northbound API definition in OpenAPI specification is out of dated.
current northbound API provided by src/alto/server/northbound/*  has more interfaces and different than openalto/alto-swagger repo.

It's better to provide/generate openapi spec of northbound API in code-first manner from src/alto/server/northbound/*.

### PR DESCRIPTION
**Pull request by itaru2622**
Fix #45

OpenAPI specification is generated from code and can be got by curl -X GET http://alto-frontend:8000/openapi.yaml
This feature is powered by https://www.django-rest-framework.org/api-guide/schemas/#generating-an-openapi-schema

### CODE REVIEW

**Comment by itaru2622** [comment]
@fno2010 clould you review this PR, please.

**Comment by fno2010** [comment]
It is a good idea to leverage OpenAPI. But I don't see the `openapi.yaml` file in this commit.

I feel the `openapi.yaml` should be a part of configuration file (`etc/alto.conf` or a YANG data instance later), or generated by the configuration.

**Comment by itaru2622** [comment]
@fno2010 thank you for reviewing and response.

I want to confirm what you meant.

I think, there is some ways to generate and provide openapi.yaml

for generation timing
a.  command execution in terminal and store it as static file.
b.  when it gets access to some REST endpoint

for providing 
1.  just provide as static file but not via REST.
2. provide via REST for the above A or B

I took choices as {B,2} in this PR at current.
in this choice, there is no gap between running source codes and openapi.yaml.

Do you mean you want to choose A as generation and configure providing way (1or 2) by configiration?
note that this choice causes a gap between source codes and openapi.yaml when developer missed executing A after modification.

 moreover,  I am wondering if A can provide correct openapi definition for running environment because REST paths can be changed  by configuration (alto.conf) at starting time.

I can add a parameter in alto.conf to controlling turn on/off {B,2} feature.

**Comment by fno2010** [comment]
@itaru2622 Many thanks for your clarification. I misunderstood this PR. I thought it was trying to use OpenAPI to generate northbound code. But clearly, I'm wrong. It provides OpenAPI spec based on the running northbound so that other tools (e.g., OAM) can read it. Then it makes sense to me.

**Pull request merged**
